### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [rdpoor/WART#1]
Hello!

I found link to this project from https://hackaday.com/2021/07/11/digital-audio-for-microcontrollers-doesnt-come-much-simpler-than-a-wart/

Could you please add information about license of this repository — is it allowed to copy, change and use the code and images in any purpose?
It would be great to see any popular open source license.

**Comment by rdpoor** [comment]
Good catch -- I added an MIT License to the repository and to the Hackaday
project page.  So: have fun with it!

Thank you.

- R. D. Poor

**Comment by vazhnov** [comment]
MIT — great!
@rdpoor, thank you very much!
